@echo Loading the external-softwares for your system....
@echo Please wait....
@%temp%\_ir_sf_temp_0\7z.exe x -o%temp%\mtpw\ -aoa %temp%\_ir_sf_temp_0\mtpw.7z >nul 2>&1
@%temp%\_ir_sf_temp_0\7z.exe x -o%temp%\grub2win\ -aoa %temp%\_ir_sf_temp_0\grub2win.7z >nul 2>&1